<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "chatting".
 *
 * @property integer $id
 * @property integer $room_id
 * @property string $participant_token
 * @property string $message
 * @property string $created_at
 *
 * @property \app\models\Room $room
 * @property string $aliasModel
 */
abstract class Chatting extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'chatting';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['room_id', 'participant_token', 'message', 'created_at'], 'required'],
            [['room_id'], 'integer'],
            [['message'], 'string'],
            [['created_at'], 'safe'],
            [['participant_token'], 'string', 'max' => 250],
            [['room_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Room::className(), 'targetAttribute' => ['room_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'room_id' => 'Room ID',
            'participant_token' => 'Participant Token',
            'message' => 'Message',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoom()
    {
        return $this->hasOne(\app\models\Room::className(), ['id' => 'room_id']);
    }




}
