<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "participant".
 *
 * @property integer $id
 * @property string $token
 * @property string $name
 * @property string $created_at
 *
 * @property \app\models\RoomParticipant[] $roomParticipants
 * @property string $aliasModel
 */
abstract class Participant extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'participant';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['token', 'name', 'created_at'], 'required'],
            [['created_at'], 'safe'],
            [['token'], 'string', 'max' => 250],
            [['name'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'token' => 'Token',
            'name' => 'Name',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoomParticipants()
    {
        return $this->hasMany(\app\models\RoomParticipant::className(), ['participant_id' => 'id']);
    }




}
