<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "room".
 *
 * @property integer $id
 * @property integer $application_id
 * @property string $token
 * @property string $created_at
 *
 * @property \app\models\Chatting[] $chattings
 * @property \app\models\Application $application
 * @property \app\models\RoomParticipant[] $roomParticipants
 * @property string $aliasModel
 */
abstract class Room extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'room';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['application_id', 'token', 'created_at'], 'required'],
            [['application_id'], 'integer'],
            [['created_at'], 'safe'],
            [['token'], 'string', 'max' => 250],
            [['application_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Application::className(), 'targetAttribute' => ['application_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'application_id' => 'Application ID',
            'token' => 'Token',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChattings()
    {
        return $this->hasMany(\app\models\Chatting::className(), ['room_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApplication()
    {
        return $this->hasOne(\app\models\Application::className(), ['id' => 'application_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoomParticipants()
    {
        return $this->hasMany(\app\models\RoomParticipant::className(), ['room_id' => 'id']);
    }




}
